### ISSUE TITLE
NoSuchElementException thrown during migration

### ISSUE THREAD

**Issue by mustafaozhan** [lupuuss/Mokkery#11]
Hello,

Thank you for this amazing mocking library, thanks to it, I get rid of ksp and decreased my build times, also finally I was able to move my project to Kotlin 2.0.

During the migration from Mockative to Mokkery I had various issues and couldn't fix 3 of them. This issue is targeting to one of it.

If you check the linked PR, I have commented out one test case. This test case was working fine with Mockative, I had to comment it during Mokkery migration since it was giving the below error:
```
java.util.NoSuchElementException at MainViewModelTest.kt:105
```

You can see the full log in the link I shared below.

Let me know if anything is needed from my end!

Log: https://github.com/Oztechan/CCC/actions/runs/9614855462/job/26520671149?pr=3579
PR: https://github.com/Oztechan/CCC/pull/3579

**Comment by lupuuss** [comment]
Hi! There is a similar problem as I described [here](https://github.com/lupuuss/Mokkery/issues/12#issuecomment-2183979613). Also, this code fragment has another problem:
```kotlin
        verify {
            analyticsManager.setUserProperty(
                UserProperty.IsPremium(
                    appStorage.premiumEndDate.isNotPassed().toString()
                )
            )
        }
```
You should not pass other mock invocation result to another invocation in verify block. Maybe this check would be enough here:
```kotlin
verify { 
   appStorage.premiumEndDate
   analtyicsManager.setUserProperty(UserProperty.IsPremium("expected-value"))
}
```

**Comment by mustafaozhan** [comment]
Thanks a lot for the explanation @lupuuss ! I confirm that the issue is not more happening when I apply your suggestions. 

There is one more issue though but I will create another issue for that since it looks like a different issue :)
