### ISSUE TITLE
NullPointerException thrown during migration

### ISSUE THREAD

**Issue by mustafaozhan** [lupuuss/Mokkery#12]
Hello,

Thank you for this amazing mocking library, thanks to it, I get rid of ksp and decreased my build times, also finally I was able to move my project to Kotlin 2.0.

During the migration from Mockative to Mokkery I had various issues and couldn't fix 3 of them. This issue is targeting to one of it.

If you check the linked PR, I have commented out one `verify` line. This line was working fine with Mockative, I had to comment it during Mokkery migration since it was giving the below error:
```
    java.lang.NullPointerException at AdControlRepositoryTest.kt:225
```

You can see the full log in the link I shared below.

Let me know if anything is needed from my end!

Log: https://github.com/Oztechan/CCC/actions/runs/9614886435/job/26546544559?pr=3581
PR: https://github.com/Oztechan/CCC/pull/3581

**Comment by lupuuss** [comment]
Hi! The first problem here is that Mokkery does not support call chains. It means that syntax below is not supported
```kotlin
every { dependency.otherDependency.call() } returns Unit
verify { dependency.otherDependency.call() }
```
You have to perform this operations directly:
```kotlin
val otherDependency = mock<OtherDependency> { every { call() } returns Unit }
every { dependency.otherDependency } returns otherDependency 
verify { otherDependency.call() }
```

The second problem is that `AdConfig` is regular instance - not a mock. In result, its calls are not tracked.

PS I see that you keep each call in single `verify` block. You can move your verifications into single `verify` block.

**Comment by mustafaozhan** [comment]
@lupuuss thank you for the expiation, this one is also resolved together with the other ones 🙂

**Comment by lupuuss** [comment]
No problem @mustafaozhan ! Thank you for reporting the issues!
