### ISSUE TITLE
no such method: ContextIndependentParameterRenderer

### ISSUE THREAD

**Issue by LambergaR** [lupuuss/Mokkery#24]
mokkery: 2.1.1
ksp: 2.0.20-Beta2-1.0.23
kotlin: 2.0.20-Beta2

When attempting migration to the latest kotlin/ksp versions we started noticing the following issue when running `./gradlew :shared:compileTestKotlinIosArm64`
```
e: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.diagnostics.rendering.ContextIndependentParameterRenderer org.jetbrains.kotlin.fir.analysis.diagnostics.FirDiagnosticRenderers.getRENDER_TYPE()'
        at dev.mokkery.plugin.diagnostics.MokkeryDiagnosticRendererFactory.<init>(MokkeryDiagnosticRendererFactory.kt:16)
        at dev.mokkery.plugin.MokkeryCompilerPluginRegistrar.registerExtensions(MokkeryCompilerPluginRegistrar.kt:21)
```
full log: [mokkery-error.log](https://github.com/user-attachments/files/16249117/mokkery-error.log)

**Comment by lupuuss** [comment]
Hi. I am aware of the issue. It is fixed [here](https://github.com/lupuuss/Mokkery/issues/9). I've planned to release it with stable 2.0.20. Is 2.0.20-Beta2 support urgent for you?

**Comment by LambergaR** [comment]
no, not at all, more than willing to wait for 2.0.20 to get a proper release :)

**Comment by lupuuss** [comment]
Duplicate of #9
