### ISSUE TITLE
Shorthand for adding mokkery-coroutines does not work

### ISSUE THREAD

**Issue by dalewking** [lupuuss/Mokkery#32]
The docs say you can do this:
```
import dev.mokkery.gradle.mokkery

dependencies {
    implementation(mokkery("coroutines")) // defaults to the current Mokkery version
}
```

but i get:

> Type mismatch: inferred type is String but Action<MokkeryGradleExtension> was expected

**Comment by lupuuss** [comment]
Could you give me a reproducer? It works in my test project.

**Comment by dalewking** [comment]
To be more specific it doesn't work for Kotlin Multiplatform projects as in:
```
kotlin {
    sourceSets {
        commonTest.dependencies {
            implementation(mokkery("coroutines"))
        }
    )
}
```

The reason is that the short hand syntax works on DependencyHandler, but those dependency blocks are actually of type `KotlinDependencyHandler` and do not extend `DependencyHandler`

**Comment by lupuuss** [comment]
I understand. I will try to add an overload in the next release.
