### ISSUE TITLE
Is not possible to mock a `data class`

### ISSUE THREAD

**Issue by alejandro-rios** [lupuuss/Mokkery#4]
I have the implementation of this data class:

```kotlin
@Serializable
data class WordPair(
    val wordsTotal: Int,
    val wordsFound: List<String>
)
```

at first run, I get this error:

`Type ''com.alejandrorios.bogglemultiplatform.data.models.WordPair'' is final and cannot be used with ''mock''!`

which I know it is because of one of the limitations of the library, then I'm including the `@OpenForMokkery` annotation to the data class, and now I get this error:

`Class ''com.alejandrorios.bogglemultiplatform.data.models.WordPair'' has no default constructor and cannot be used with ''mock''!`

Is it possible to solve this without adding default values to the data class?, maybe I'm missing something else.

**Comment by lupuuss** [comment]
Yes, in the current version, any open/abstract class (including classes "opened" with the all-open plugin) must have a default constructor. I have plans to remove this limitation, but I'm not sure when it will happen.

Also, why do you need to mock a data class? It should be easier to just create an instance for tests instead of mocking it.

**Comment by alejandro-rios** [comment]
> Yes, in the current version, any `open`/`abstract` class (including classes "opened" with the `all-open` plugin) must have a default constructor. I have plans to remove this limitation, but I'm not sure when it will happen.
> 
> Also, why do you need to mock a `data class`? It should be easier to just create an instance for tests instead of mocking it.

Hello @lupuuss, thanks for responding so fast, at the end I'm using the instance as you mentioned, but I wanted to check with you if the `mock` was possible.

**Comment by lupuuss** [comment]
"I've created #5 that directly describes this limitation, so I'm closing this issue.
