### ISSUE TITLE
Creating mocks not working as expected in KMP

### ISSUE THREAD

**Issue by dthomson117** [lupuuss/Mokkery#41]
When attempting to create a mock at the top of a test class like 

`private val mockedObject = mock<AClass>()`

Where the AClass is open via `openAll` plugin and creating a class to test via 

```
@BeforeTest
    fun setUp() {
        sut =
            ClassToTest(
                param = mockedObject ,
            )
    }
```

When attempting to modify an answer for the mocked object via 
`every { mockedObject .foo() } returns bar`

I get the following error:
`dev.mokkery.internal.NotSingleCallInEveryBlockException: Each 'every' block requires single mock call!`

When Mokking the call in the block however it works as expected:
```
mock<AClass>() {
    every { mockedObject .foo() } returns bar
}
```

Running Kotlin Multiplatform v2.0.20, with the test in `shared/commonTest`, using Mokkery 2.3.0

**Comment by lupuuss** [comment]
Hi! Could you provide me a reproducer?

**Comment by dthomson117** [comment]
Hi, when trying to recreate this in a separate project everything worked as expected. Managed to get it working in my original project as well.

Seems to have been a Gradle issue, after upgrading Android Studio to Koala 2024.1.2, upgrading AGP from 8.3 -> 8.4.2 I saw no affect until replacing the deprecated
```
kotlinOptions {
                jvmTarget = "1.8"
            }
```

with 

```
compileTaskProvider.configure {
                compilerOptions {
                    jvmTarget.set(JvmTarget.JVM_1_8)
                }
            }
```

Not exactly sure why this fixed the issue mentioned above, but if anyone else is having a similar issue it might be worth trying this fix :)

**Comment by dthomson117** [comment]
Apologies after trying multiple things I can't seem to reproduce in a separate project. Also tried updating everything on my end and nothing seems to have fixed it. Error seems sporadic too, where sometimes the test passes but will then fail later with the above error message.

If possible, could I add you to my private repo with the error so you can look?

**Comment by lupuuss** [comment]
Yes, I can take a look.

**Comment by lupuuss** [comment]
@dthomson117 
I figured it out! The error message that you get in you project is actually correct. During `every { ... }` there is more than one call to the mock of `StartupRepository`:
1. In `every { ... }` - this is expected
2. `ActiveSplitManager` (initialized before each test)  starts a coroutine in the constructor, which calls method of the mock - this one must not be called

[Mokkery mocks must not be called from other threads while configuring or verifying.](https://mokkery.dev/docs/Thread_safety). The problem does not occur always as multithreading is not deterministic and sometimes the calls were not executed simultaneously.

**Comment by dthomson117** [comment]
Ah that's brilliant thank you for finding that!

**Comment by dthomson117** [comment]
Just to add to this, adding an `every { . . . }` to the `@BeforeTest` function that is called during init seems to have fixed the issue as well without having to modify the original class
