### ISSUE TITLE
Mocking `abstract`/`open` classes requires default constructor

### ISSUE THREAD

**Issue by lupuuss** [lupuuss/Mokkery#5]
Currently, Mokkery requires `abstract`/`open` classes to have a default constructor, and it should be possible to remove this requirement.

This limitation was partially mentioned in #4 .

**Comment by Nillerr** [comment]
Hi @lupuuss!

Happy to have come across another mocking framework for Kotlin Multiplatform!

The way we solved this in [mockative/mockative](https://github.com/mockative/mockative) was by recursively generating mocks (and default values) for the parameters of the default constructor. This also automatically enables implicit chain-mocking like this:

```kotlin
interface LibraryClient {
    val books: BooksRepository
}

val client = mock<LibraryClient>()

@Test
fun test() {
    everySuspend { client.books.findById(id) } calls { (id: String  -> Book(id) }
} 
```

This assumes the consumer is also using the `all-open` plugin. You may be able to do something similar in your Mokkery 🙂
