### ISSUE TITLE
Could not resolve dev.mokkery:mokkery-gradle:2.4.0 for iOs[...]Test targets in KMP project

### ISSUE THREAD

**Issue by RikNorakomi** [lupuuss/Mokkery#50]
I can't seem to get mokkery setup correctly in my KMP project
In my build.gradle.kts script I have added the depency for mokkery in the following way:
```
plugins {
    ...
    id("dev.mokkery") version libs.versions.mokkery
}

kotlin {
   sourceSets {
        ...
        commonTest {
            dependencies {
            ...
            implementation(libs.mokkery)
            }
        }
   }
}
```

I only want to provide mokkery for my commonTest package, but when I sync gradle I get a `Could not resolve dev.mokkery:mokkery-gradle:2.4.0` for multiple iOS targets (iosArm64Test, iosSimulatorArm64Test, iosX64Test).

Anyone know how to solve this?

**Comment by lupuuss** [comment]
Hi! `dev.mokkery:mokkery-gradle:2.4.0` is a gradle dependency (jvm only) and you must not specify it like this.

You only need this part:
```kotlin
plugins {
    ...
    id("dev.mokkery") version libs.versions.mokkery
}
```

Runtime dependency is called `dev.mokkery:mokkery-runtime` (this one is multiplatform) and it is applied automatically by the plugin and you don't have to do it manually.

**Comment by lupuuss** [comment]
@RikNorakomi did this solve your problem?
