### ISSUE TITLE
Mocking outside of mock block

### ISSUE THREAD

**Issue by bDev10** [lupuuss/Mokkery#58]
Seems like mocking outside of `mock()` function's `block` parameter is not working, although [documentation suggests it should work](https://mokkery.dev/docs/Guides/Mocking#defining-answers). E.g. for:
```kotlin
val repository = mock<BookRepository>()
every { repository.findAll() } returns flowOf(Book(...))
```
We get error:
```
Call BookRepository(1).findAll() not mocked!
```

When `every` is called from the `block` parameter, mocking works:
```kotlin
val repository = mock<BookRepository>() {
    every { findAll() } returns flowOf(Book(...))
}
```

Checked on version `2.5.0`.

Would be useful to have this feature working e.g. for cases where mocked instance is created outside of test function and we want specify mocking behavior expected for specific test case.

**Comment by lupuuss** [comment]
Hi! Could you provide me a reproducer? I'm not able to reproduce it based on your samples.

**Comment by bDev10** [comment]
Hi, I'm sorry it was my fault, so false alarm.
Not spot that the class with injected mock called the yet unmocked function in init block, so just mock was called earlier then I expected when I wrote the test and the error was legit!
